name: Target Environment
author: OlivierP-SP
description: Determine which env to deploy a repo
inputs:
  target-host:
    description: 'Where to deploy'
    required: true
outputs:
  host: # id of the output
    description: 'Host where the repo will deployed to'
    value: ${{fromJSON(steps.set-hosts-matrix.outputs.hosts-matrix) }} #steps.set-hosts-matrix.outputs.hosts-matrix
runs:
  using: "composite"
  steps:
    - id: set-hosts-matrix
      run: echo "::set-output name=hosts-matrix::{\"prod\":\"smartpush\",\"recette1\":\"smartpush_recette1\"}"
      shell: bash
