name: Target Environment
author: OlivierP-SP
description: Determine which env to deploy a repo
outputs:
  host: # id of the output
    description: 'Host where the repo will deployed to'
    value: ${{ steps.set-hosts-matrix.outputs.hosts-matrix }} #steps.set-hosts-matrix.outputs.hosts-matrix
  env: # id of the output
    description: 'Environment option to build app'
    value: ${{ steps.set-env-matrix.outputs.env-matrix }} #steps.set-hosts-matrix.outputs.hosts-matrix
  data-host: # id of the output
    description: 'Data Host where the repo will deployed to'
    value: ${{ steps.set-data-hosts-matrix.outputs.data-hosts-matrix }} 
  data-env: # id of the output
    description: 'Data Environment option to build app'
    value: ${{ steps.set-data-env-matrix.outputs.data-env-matrix }}

runs:
  using: "composite"
  steps:
    - id: set-hosts-matrix
      run: echo "hosts-matrix={\"prod\":\"smartpush\",\"master\":\"smartpush\",\"preprod\":\"smartpush_preprod\",\"develop\":\"smartpush_preprod\",\"recette1\":\"smartpush_recette1\",\"recette2\":\"smartpush_recette2\",\"recette3\":\"smartpush_recette3\"}" >> $GITHUB_OUTPUT
      shell: bash
    - id: set-env-matrix
      run: echo "env-matrix={\"master\":\"prod\",\"develop\":\"preprod\"}" >> $GITHUB_OUTPUT
      shell: bash
    - id: set-data-hosts-matrix
      run: echo "data-hosts-matrix={\"prod\":\"smartpushpython\",\"main\":\"smartpushpython\",\"preprod\":\"smartpushpythonpp\",\"develop\":\"smartpushpythonpp\",\"recette1\":\"smartpushpython_recette1\",\"recette2\":\"smartpushpython_recette2\",\"recette3\":\"smartpushpython_recette3\"}" >> $GITHUB_OUTPUT
      shell: bash
    - id: set-data-env-matrix
      run: echo "data-env-matrix:={\"main\":\"prod\",\"develop\":\"preprod\"}" >> $GITHUB_OUTPUT
      shell: bash
