name: Node Code analysis
on:
  workflow_call:
    inputs:
      src_path:
        description: path to source code
        type: string
        required: false
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  code-analysis-node:
    name: Execute CI in Node context
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      -   name: Build Sources
          run: |
            npm install
            npm run build
      - name: Upload analysis files artifact
        uses: actions/upload-artifact@v3
        id: upload-artifact
        with:
          name: analysis-workflow-artifact
          path: dist/apps/
          retention-days: 1
          if-no-files-found: error