name: Node Code analysis
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  code-analysis-php:
    name: Execute CI in Node context
    runs-on: ubuntu-latest
    # runs only when pushing to a branch other than develop or master, or when creating a pull request on master or develop
    if: github.event_name == 'pull_request' && github.event.action != 'closed' && contains(toJSON('["develop", "master"]'), github.base_ref)
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3